name: 'notifychanges'
description: 'Notifies other repos about changes'
author: 'Nodes'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'Rasmus'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
