name: 'notifychanges'
description: 'Notifies other repos about changes'
author: 'Nodes'
inputs: 
  trigger:
    description: 'Github repository that triggered this action'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.trigger }}
