name: 'notifychanges'
description: 'Notifies other repos about changes'
author: 'Nodes'
inputs: 
  trigger:
    description: 'Github repository that triggered this action'
    default: ''
  circle_token:
    description: 'Token for Circle CI API'
    defaut: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.trigger }}
    - ${{ inputs.circle_token }}
