name: 'notifychanges'
description: 'Notifies other repos about changes'
author: 'Nodes'
inputs: 
  dev1:
    description: '1st developer'
    default: 'Siemen'
  dev2:
    description: '2nd developer'
    default: 'Jesper'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dev1 }}
    - ${{ inputs.dev2 }}
